# Generated by Django 5.1 on 2025-06-30 12:28

import apps.core.models.abstracts
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fin", "0013_compensation_document"),
        ("hr", "0002_employee_hr_employee_firstna_7af8e7_idx_and_more"),
        ("org", "0005_alter_position_order_alter_status_is_payable"),
        ("trans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("january", "January"),
                            ("february", "February"),
                            ("march", "March"),
                            ("april", "April"),
                            ("may", "May"),
                            ("june", "June"),
                            ("july", "July"),
                            ("august", "August"),
                            ("september", "September"),
                            ("october", "October"),
                            ("november", "November"),
                            ("december", "December"),
                        ],
                        default="january",
                        max_length=255,
                        verbose_name="month",
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("q1", "First Quarter"),
                            ("q2", "Second Quarter"),
                            ("q3", "Third Quarter"),
                            ("q4", "Fourth Quarter"),
                        ],
                        default="q1",
                        max_length=255,
                        verbose_name="quarter",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=20, verbose_name="debit"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=20,
                        verbose_name="credit",
                    ),
                ),
                (
                    "amount",
                    models.GeneratedField(
                        db_persist=False,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("debit"), "-", models.F("credit")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=4, max_digits=20
                        ),
                        verbose_name="amount",
                    ),
                ),
                (
                    "fiscal_object_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="fiscal object id"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, default="", verbose_name="explanation"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("compensation", "tax")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journals",
                        to="org.costcenter",
                        verbose_name="cost center",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journals",
                        to="hr.employee",
                        verbose_name="employee",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journals",
                        to="fin.period",
                        verbose_name="period",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journals",
                        to="trans.voucher",
                        verbose_name="voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ("-date", "-created_at"),
                "permissions": (
                    ("export_journalentry", "Can export journal entry"),
                    ("view_activity_journalentry", "Can view journal entry activity"),
                ),
            },
            bases=(apps.core.models.abstracts.UrlsMixin, models.Model),
        ),
    ]
