# Generated by Django 5.1 on 2025-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchertransaction",
            name="net",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, verbose_name="net"
            ),
        ),
        migrations.AddField(
            model_name="vouchertransaction",
            name="total",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, verbose_name="total"
            ),
        ),
    ]
