# Generated by Django 5.1 on 2025-06-07 21:49

import apps.core.models.abstracts
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0011_voucherkind"),
        ("hr", "0005_alter_employee_identity_document_and_more"),
        ("trans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vouchers",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"],
                        message="the field must be a valid pdf, png, jpg or jpeg file.",
                    )
                ],
                verbose_name="document",
            ),
        ),
        migrations.CreateModel(
            name="VoucherTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="quantity"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="value"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "compensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="fin.compensation",
                        verbose_name="compensation",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="hr.employee",
                        verbose_name="employee",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="trans.voucher",
                        verbose_name="voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher Transaction",
                "verbose_name_plural": "Voucher Transactions",
                "ordering": ("-voucher__date", "voucher__voucher_serial", "ordering"),
                "permissions": (
                    ("export_vouchertransaction", "Can export voucher transaction"),
                    (
                        "view_activity_vouchertransaction",
                        "Can view voucher transaction activity",
                    ),
                ),
            },
            bases=(apps.core.models.abstracts.UrlsMixin, models.Model),
        ),
    ]
