# Generated by Django 5.1 on 2025-06-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0002_alter_voucher_document_vouchertransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchertransaction",
            name="tax",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, verbose_name="tax"
            ),
        ),
        migrations.AlterField(
            model_name="vouchertransaction",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=20, verbose_name="quantity"
            ),
        ),
        migrations.AlterField(
            model_name="vouchertransaction",
            name="value",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=20, verbose_name="value"
            ),
        ),
    ]
