# Generated by Django 5.1 on 2025-07-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0015_alter_compensation_shortname"),
        ("trans", "0002_journalentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchertransaction",
            name="compensation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="fin.compensation",
                verbose_name="compensation",
            ),
        ),
        migrations.AlterField(
            model_name="vouchertransaction",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="trans.voucher",
                verbose_name="voucher",
            ),
        ),
    ]
