# Generated by Django 5.1 on 2025-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0003_alter_vouchertransaction_compensation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ("-date", "ordering"),
                "permissions": (
                    ("export_journalentry", "Can export journal entry"),
                    ("view_activity_journalentry", "Can view journal entry activity"),
                ),
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
