# Generated by Django 5.1 on 2025-06-08 14:42

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0003_vouchertransaction_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vouchers",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"],
                        message="the field must be a valid pdf, png, jpg or jpeg file.",
                    ),
                    apps.core.validators.validate_pdf_image_mimetype,
                ],
                verbose_name="document",
            ),
        ),
    ]
