# Generated by Django 5.1 on 2025-07-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0004_alter_journalentry_options_journalentry_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ("date", "ordering", "-debit"),
                "permissions": (
                    ("export_journalentry", "Can export journal entry"),
                    ("view_activity_journalentry", "Can view journal entry activity"),
                ),
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="voucher",
            options={
                "ordering": ("is_migrated", "date", "-created_at", "voucher_serial"),
                "permissions": (
                    ("export_voucher", "Can export voucher"),
                    ("migrate_voucher", "Can migrate voucher"),
                    ("unmigrate_voucher", "Can unmigrate voucher"),
                    ("audit_voucher", "Can audit voucher"),
                    ("unaudit_voucher", "Can unaudit voucher"),
                    ("view_activity_voucher", "Can view voucher activity"),
                ),
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
            },
        ),
        migrations.AlterModelOptions(
            name="vouchertransaction",
            options={
                "ordering": (
                    "voucher__is_migrated",
                    "voucher__date",
                    "-voucher__created_at",
                    "voucher__voucher_serial",
                    "ordering",
                ),
                "permissions": (
                    ("export_vouchertransaction", "Can export voucher transaction"),
                    (
                        "view_activity_vouchertransaction",
                        "Can view voucher transaction activity",
                    ),
                ),
                "verbose_name": "Voucher Transaction",
                "verbose_name_plural": "Voucher Transactions",
            },
        ),
    ]
