# Generated by Django 5.1 on 2025-07-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0005_alter_journalentry_options_alter_voucher_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ("general_serial", "ordering", "-debit"),
                "permissions": (
                    ("export_journalentry", "Can export journal entry"),
                    ("view_activity_journalentry", "Can view journal entry activity"),
                ),
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="general_serial",
            field=models.PositiveBigIntegerField(
                default=0, editable=False, verbose_name="general serial"
            ),
        ),
    ]
