# Generated by Django 5.1 on 2025-07-29 09:32

import apps.core.models.setting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_page_size",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="max page size for pagination purposes",
                        verbose_name="max page size",
                    ),
                ),
                (
                    "per_page",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="per page for pagination purposes",
                        verbose_name="per page",
                    ),
                ),
                (
                    "messages_timeout",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="messages timeout in seconds",
                        verbose_name="messages timeout",
                    ),
                ),
                (
                    "critical_confirmation_timeout",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="critical confirmation timeout in seconds",
                        verbose_name="critical confirmation timeout",
                    ),
                ),
                (
                    "per_page_list",
                    models.JSONField(
                        default=apps.core.models.setting.default_per_page_list,
                        help_text="per page list for pagination purposes",
                        verbose_name="per page list",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Settings",
                "ordering": ("id",),
            },
        ),
    ]
