# Generated by Django 5.1 on 2025-07-28 12:20

from django.db import migrations, models

import apps.core.models.abstracts


def create_globalsetting(apps, schema_editor):
    GlobalSetting = apps.get_model("core", "GlobalSetting")
    GlobalSetting.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_page_size",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="max page size for pagination purposes",
                        verbose_name="max page size",
                    ),
                ),
                (
                    "per_page",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="per page for pagination purposes",
                        verbose_name="per page",
                    ),
                ),
                (
                    "messages_timeout",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="messages timeout in seconds",
                        verbose_name="messages timeout",
                    ),
                ),
                (
                    "critical_confirmation_timeout",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="delete confirmation timeout in seconds",
                        verbose_name="delete confirmation timeout",
                    ),
                ),
                (
                    "per_page_list",
                    models.JSONField(
                        default=list,
                        help_text="per page list for pagination purposes",
                        verbose_name="per page list",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Setting",
                "verbose_name_plural": "Global Settings",
                "ordering": ("id",),
            },
            bases=(apps.core.models.abstracts.SingletonModelMixin, models.Model),
        ),
        migrations.RunPython(create_globalsetting),
    ]
