# Generated by Django 5.1 on 2025-07-08 16:47
from pathlib import Path

import django.core.validators
import django.db.models.deletion
from django.apps import AppConfig
from django.core.files import File
from django.db import migrations, models

import apps.core.validators


def create_default_template(apps: AppConfig, schema_editor):
    empty_template = Path("assets/word_templates/empty.docx").resolve()

    Template = apps.get_model("core", "Template")
    TemplateSetting = apps.get_model("core", "TemplateSetting")

    with open(empty_template, "rb") as file:
        voucher_template = Template()
        voucher_template.name = "voucher"
        voucher_template.file.save("template.docx", File(file))

    voucher_template.save()
    TemplateSetting.objects.create(voucher=voucher_template)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="templates",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx"],
                                message="the field must be a valid docx file.",
                            ),
                            apps.core.validators.validate_docx_mimetype,
                        ],
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TemplateSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_settings",
                        to="core.template",
                        verbose_name="setting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Setting",
                "verbose_name_plural": "Template Settings",
                "ordering": ("voucher__name",),
            },
        ),
        migrations.RunPython(create_default_template),
    ]
