# Generated by Django 5.1 on 2025-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_globalsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsetting",
            name="per_page_list",
            field=models.JSONField(
                default=list,
                help_text="per page list for pagination purposes",
                verbose_name="per page list",
            ),
        ),
    ]
