# Generated by Django 5.1 on 2025-04-02 18:01

import django.core.validators
from django.apps import AppConfig
from django.db import migrations, models
from django.utils.text import slugify

import apps.core.mixins.save


def create_default_currency(apps: AppConfig, schema_editor):
    name = "الليرة السورية"
    Currency = apps.get_model("fin", "Currency")
    Currency.objects.create(
        name=name,
        symbol="ل.س",
        code="SYR",
        fraction_name="قرش",
        is_primary=True,
        slug=slugify(name, allow_unicode=True),
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=10, verbose_name="symbol")),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 3-letter currency code",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "fraction_name",
                    models.CharField(max_length=20, verbose_name="fraction name"),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="standard number of decimal places for this currency",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="is it primary or secondary currency?",
                        verbose_name="is primary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ("-is_primary", "name"),
                "permissions": (
                    ("export_currency", "Can export currency"),
                    ("view_activity_currency", "Can view currency activity"),
                ),
            },
            bases=(apps.core.mixins.save.AddCreateActivityMixin, models.Model),
        ),
        migrations.RunPython(
            create_default_currency, reverse_code=migrations.RunPython.noop
        ),
    ]
