# Generated by Django 5.1 on 2025-04-03 19:35
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.apps import AppConfig
from django.db import migrations, models

import apps.core.mixins.save
import apps.core.models.abstracts


def create_initial_exchange_rate(apps: AppConfig, schema_editor):
    Currency = apps.get_model("fin", "Currency")
    ExchangeRate = apps.get_model("fin", "ExchangeRate")

    default_currency = Currency.objects.order_by("id").first()
    ExchangeRate.objects.create(
        currency=default_currency,
        rate=1,
        date=django.utils.timezone.datetime(2010, 1, 1).date(),
        notes="initial exchange rate",
        slug=uuid.uuid4().hex,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("fin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                help_text="ISO 4217 3-letter currency code",
                max_length=3,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="standard number of decimal places for this currency",
                verbose_name="decimal places",
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="rate"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", max_length=1000, verbose_name="notes"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="fin.currency",
                        verbose_name="currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ("-created_at", "-date"),
                "permissions": (
                    ("export_exchangerate", "Can export exchange rate"),
                    ("view_activity_exchangerate", "Can view exchange rate activity"),
                ),
            },
            bases=(
                apps.core.models.abstracts.UrlsMixin,
                apps.core.mixins.save.AddCreateActivityMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(
            code=create_initial_exchange_rate,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
