# Generated by Django 5.1 on 2025-05-25 04:42

import apps.core.mixins.save
import apps.core.models.abstracts
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("fixed", models.BooleanField(default=True, verbose_name="fixed")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="rate",
                    ),
                ),
                (
                    "rounded_to",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="rounded to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
                "ordering": ("name",),
                "permissions": (
                    ("export_tax", "Can export tax"),
                    ("view_activity_tax", "Can view tax activity"),
                ),
            },
            bases=(
                apps.core.mixins.save.AddCreateActivityMixin,
                apps.core.models.abstracts.UrlsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_from",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount from",
                    ),
                ),
                (
                    "amount_to",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount to",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="rate",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brackets",
                        to="fin.tax",
                        verbose_name="tax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Bracket",
                "verbose_name_plural": "Tax Brackets",
                "ordering": ("amount_from",),
                "permissions": (
                    ("export_taxbracket", "Can export tax bracket"),
                    ("view_activity_taxbracket", "Can view tax bracket activity"),
                ),
            },
            bases=(
                apps.core.mixins.save.AddCreateActivityMixin,
                apps.core.models.abstracts.UrlsMixin,
                models.Model,
            ),
        ),
    ]
