# Generated by Django 5.1 on 2025-07-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="kind",
            field=models.CharField(
                choices=[("benefit", "Benefit"), ("cut", "Cut")],
                default="benefit",
                max_length=10,
                verbose_name="kind",
            ),
        ),
    ]
