# Generated by Django 5.1 on 2025-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="max_total",
            field=models.DecimalField(
                decimal_places=4,
                default=500000000,
                help_text="max total value to calculate the compensation value",
                max_digits=20,
                verbose_name="max total value",
            ),
        ),
        migrations.AddField(
            model_name="compensation",
            name="min_total",
            field=models.DecimalField(
                decimal_places=4,
                default=-500000000,
                help_text="min total value to calculate the compensation value",
                max_digits=20,
                verbose_name="min total value",
            ),
        ),
        migrations.AddField(
            model_name="compensation",
            name="restrict_to_max_total_value",
            field=models.TextField(
                choices=[("replace", "Replace"), ("raise_error", "Raise Error")],
                default="raise_error",
                help_text="if Raise error, it will raise an error if the total value is greater than max total value, otherwise it will replace the value with max total value",
                verbose_name="restrict to max total value",
            ),
        ),
        migrations.AddField(
            model_name="compensation",
            name="restrict_to_min_total_value",
            field=models.TextField(
                choices=[("replace", "Replace"), ("raise_error", "Raise Error")],
                default="raise_error",
                help_text="if Raise error, it will raise an error if the total value is less than min total value, otherwise it will replace the value with min total value",
                verbose_name="restrict to min total value",
            ),
        ),
    ]
