# Generated by Django 5.1 on 2025-05-25 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0002_tax_taxbracket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={
                "ordering": ("fixed", "name"),
                "permissions": (
                    ("export_tax", "Can export tax"),
                    ("view_activity_tax", "Can view tax activity"),
                ),
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
            },
        ),
        migrations.AlterModelOptions(
            name="taxbracket",
            options={
                "ordering": ("tax", "amount_from", "amount_to"),
                "permissions": (
                    ("export_taxbracket", "Can export tax bracket"),
                    ("view_activity_taxbracket", "Can view tax bracket activity"),
                ),
                "verbose_name": "Tax Bracket",
                "verbose_name_plural": "Tax Brackets",
            },
        ),
        migrations.AddField(
            model_name="tax",
            name="round_method",
            field=models.CharField(
                choices=[("round", "Round"), ("floor", "Floor"), ("ceil", "Ceil")],
                default="ceil",
                max_length=10,
                verbose_name="round method",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="rounded_to",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="rounded to",
            ),
        ),
    ]
