# Generated by Django 5.1 on 2025-08-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0002_compensation_max_total_compensation_min_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="max_total_formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        <strong>Formula to calculate compensation max total value</strong>\n        <ul>\n            <li>- It should be a valid python expression</li>\n            <li>- It should return a decimal number</li>\n            <li>- You can use (compensation, employee and quantity) objects to calculate the value if based on any one of them</li>\n            <li>- You can use underscores (_) to separate numbers as thousands</li>\n        </ul>\n        ",
                verbose_name="max total formula",
            ),
        ),
        migrations.AddField(
            model_name="compensation",
            name="min_total_formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        <strong>Formula to calculate compensation min total value</strong>\n        <ul>\n            <li>- It should be a valid python expression</li>\n            <li>- It should return a decimal number</li>\n            <li>- You can use (compensation, employee and quantity) objects to calculate the value if based on any one of them</li>\n            <li>- You can use underscores (_) to separate numbers as thousands</li>\n        </ul>\n        ",
                verbose_name="min total formula",
            ),
        ),
    ]
