# Generated by Django 5.1 on 2025-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0004_alter_tax_round_method_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="compensation",
            name="formula",
            field=models.TextField(
                blank=True,
                default="",
                help_text="\n        <strong>Formula to calculate compensation value</strong>\n        <ul>\n            <li>- It should be a valid python expression</li>\n            <li>- It should return a decimal number</li>\n            <li>- Always use `obj` as argument</li>\n            <li>- You can use underscores (_) to separate numbers as thousands</li>\n        </ul>\n        ",
                verbose_name="formula",
            ),
        ),
    ]
