# Generated by Django 5.1 on 2025-06-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0005_compensation_is_active_alter_compensation_formula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compensation",
            options={
                "ordering": ("-is_active", "tax__name", "calculation_method", "name"),
                "permissions": (
                    ("export_compensation", "Can export compensation"),
                    ("view_activity_compensation", "Can view compensation activity"),
                ),
                "verbose_name": "Compensation",
                "verbose_name_plural": "Compensations",
            },
        ),
    ]
