# Generated by Django 5.1 on 2025-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0007_compensation_max_value_compensation_min_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensation",
            name="affected_by_working_days",
            field=models.BooleanField(
                default=False, verbose_name="affected by working days"
            ),
        ),
    ]
