# Generated by Django 5.1 on 2025-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0008_alter_compensation_affected_by_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="accounting_id",
            field=models.CharField(
                default="31",
                help_text="cost center id in accounting system",
                max_length=15,
                verbose_name="cost center id",
            ),
        ),
    ]
