# Generated by Django 5.1 on 2025-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0009_compensation_accounting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensation",
            name="accounting_id",
            field=models.CharField(
                blank=True,
                default="31",
                help_text="accounting id in accounting system (in chart of accounts)",
                max_length=15,
                null=True,
                verbose_name="accounting id",
            ),
        ),
    ]
