# Generated by Django 5.1 on 2025-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0011_voucherkind"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="shortname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="to use it in services like sms, whatsapp, etc.",
                max_length=255,
                verbose_name="short name",
            ),
        ),
    ]
