# Generated by Django 5.1 on 2025-06-21 23:03

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0012_compensation_shortname"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensation",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="compensations",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"],
                        message="the field must be a valid pdf, png, jpg or jpeg file.",
                    ),
                    apps.core.validators.validate_pdf_image_mimetype,
                ],
                verbose_name="document",
            ),
        ),
    ]
