# Generated by Django 5.1 on 2025-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0013_compensation_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="affected_by_working_days",
            field=models.BooleanField(
                default=False, verbose_name="affected by working days"
            ),
        ),
    ]
