# Generated by Django 5.1 on 2025-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fin", "0014_tax_affected_by_working_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensation",
            name="shortname",
            field=models.CharField(
                help_text="to use it in services like sms, whatsapp, etc.",
                max_length=255,
                verbose_name="short name",
            ),
        ),
    ]
