# Generated by Django 5.1 on 2025-06-25 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0005_alter_degree_is_academic_alter_degree_order_and_more"),
        ("geo", "0005_alter_nationality_is_local"),
        ("hr", "0001_initial"),
        ("org", "0005_alter_position_order_alter_status_is_payable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["firstname", "father_name", "lastname"],
                name="hr_employee_firstna_7af8e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["birth_date"], name="hr_employee_birth_d_0b04ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["hire_date"], name="hr_employee_hire_da_4d71d0_idx"
            ),
        ),
    ]
