# Generated by Django 5.1 on 2025-03-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={
                "ordering": ("kind", "email"),
                "verbose_name": "email",
                "verbose_name_plural": "emails",
            },
        ),
        migrations.AlterModelOptions(
            name="mobile",
            options={
                "ordering": ("kind", "number"),
                "verbose_name": "mobile",
                "verbose_name_plural": "mobiles",
            },
        ),
        migrations.AlterModelOptions(
            name="phone",
            options={
                "ordering": ("kind", "number"),
                "verbose_name": "phone",
                "verbose_name_plural": "phones",
            },
        ),
        migrations.AddField(
            model_name="email",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mobile",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phone",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
