# Generated by Django 5.1 on 2025-07-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_employee_hr_employee_firstna_7af8e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": (
                    "cost_center__name",
                    "job_subtype__name",
                    "specialization__name",
                    "degree__name",
                    "fullname",
                ),
                "permissions": (
                    ("export_employee", "Can export employee"),
                    ("view_activity_employee", "Can view employee activity"),
                ),
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
