# Generated by Django 5.1 on 2025-03-21 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_alter_degree_name_alter_school_name_and_more"),
        ("geo", "0004_alter_city_governorate_alter_city_kind_and_more"),
        ("hr", "0002_alter_email_options_alter_mobile_options_and_more"),
        ("org", "0004_alter_costcenter_name_alter_group_kind_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(verbose_name="birth date"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="card_date",
            field=models.DateField(blank=True, null=True, verbose_name="card date"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="geo.city",
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="org.costcenter",
                verbose_name="cost center",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="current address"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="edu.degree",
                verbose_name="degree",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                to="org.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="identity_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="identities",
                verbose_name="identity document",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_subtype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="org.jobsubtype",
                verbose_name="job subtype",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="martial_status",
            field=models.CharField(
                choices=[
                    ("married", "Married"),
                    ("single", "Single"),
                    ("divorced", "Divorced"),
                    ("other", "Other"),
                ],
                default="single",
                max_length=30,
                verbose_name="martial status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="military_status",
            field=models.CharField(
                choices=[
                    ("defremented", "Defremented"),
                    ("in progress", "In Progress"),
                    ("finished", "Finished"),
                    ("excused", "Excused"),
                    ("other", "Other"),
                ],
                default="excused",
                max_length=30,
                verbose_name="military status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nationality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="geo.nationality",
                verbose_name="nationality",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="org.position",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles", verbose_name="profile"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="religion",
            field=models.CharField(
                choices=[
                    ("muslim", "Muslim"),
                    ("christian", "Christian"),
                    ("jewish", "Jewish"),
                    ("other", "Other"),
                ],
                default="muslim",
                max_length=30,
                verbose_name="religion",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="edu.school",
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="edu.specialization",
                verbose_name="specialization",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="org.status",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
