# Generated by Django 5.1 on 2025-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_employee_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_employee_age",
                    models.PositiveIntegerField(
                        default=18,
                        help_text="allowed min employee age",
                        verbose_name="min employee age",
                    ),
                ),
                (
                    "nth_job_anniversary",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="years count to calculate job anniversary",
                        verbose_name="nth job anniversary",
                    ),
                ),
                (
                    "years_count_to_group_job_age",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="years count to group job age",
                        verbose_name="years count to group job age",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hr Settings",
                "ordering": ("id",),
            },
        ),
    ]
