# Generated by Django 5.1 on 2025-07-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="separation_date",
            field=models.DateField(
                blank=True,
                help_text="if the employee has been separated from the institution",
                null=True,
                verbose_name="separation date",
            ),
        ),
    ]
