# Generated by Django 5.1 on 2025-03-25 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_birth_date_alter_employee_card_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="mobile",
            name="number",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="the field must be syrian mobile number like 0947302503.",
                        regex="^09\\d{8}$",
                    )
                ],
                verbose_name="mobile number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phone",
            unique_together={("employee", "number")},
        ),
    ]
