# Generated by Django 5.1 on 2025-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_employee_separation_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": (
                    "-status__is_payable",
                    "status__name",
                    "cost_center__name",
                    "job_subtype__name",
                    "specialization__name",
                    "degree__name",
                    "fullname",
                ),
                "permissions": (
                    ("export_employee", "Can export employee"),
                    ("view_activity_employee", "Can view employee activity"),
                ),
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="separation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="separation date"
            ),
        ),
    ]
