# Generated by Django 5.1 on 2025-06-08 14:42

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_alter_employee_identity_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="identity_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="identities",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg"],
                        message="the field must be a valid pdf, png, jpg or jpeg file.",
                    ),
                    apps.core.validators.validate_pdf_image_mimetype,
                ],
                verbose_name="identity document",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="profile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"],
                        message="the field must be a valid jpg, jpeg or png file.",
                    ),
                    apps.core.validators.validate_image_mimetype,
                ],
                verbose_name="profile",
            ),
        ),
    ]
