# Generated by Django 5.1 on 2025-06-21 09:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_alter_employee_identity_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="father_fullname",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.functions.text.Concat(
                    models.F("father_name"), models.Value(" "), models.F("lastname")
                ),
                output_field=models.CharField(max_length=255),
                verbose_name="father full name",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="fullname",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.functions.text.Concat(
                    models.F("firstname"),
                    models.Value(" "),
                    models.F("father_name"),
                    models.Value(" "),
                    models.F("lastname"),
                ),
                output_field=models.CharField(max_length=255),
                verbose_name="full name",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shortname",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.functions.text.Concat(
                    models.F("firstname"), models.Value(" "), models.F("lastname")
                ),
                output_field=models.CharField(max_length=255),
                verbose_name="short name",
            ),
        ),
    ]
