# Generated by Django 5.1 on 2025-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_employee_father_fullname_employee_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="autocomplete",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="for autocomplete search",
                max_length=1000,
                verbose_name="autocomplete",
            ),
        ),
    ]
