# Generated by Django 5.1 on 2025-03-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ("kind", "name"),
                "permissions": (
                    ("export_group", "Can export group"),
                    ("view_activity_group", "Can view group activity"),
                ),
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
    ]
