# Generated by Django 5.1 on 2025-02-14 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtype",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_jobtype", "Can export job_type"),
                    ("view_activity_jobtype", "Can view job_type activity"),
                ),
                "verbose_name_plural": "job_types",
            },
        ),
        migrations.CreateModel(
            name="JobSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_subtypes",
                        to="org.jobtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "job_subtypes",
                "ordering": ("job_type__name", "name"),
                "permissions": (
                    ("export_jobsubtype", "Can export job_subtype"),
                    ("view_activity_jobsubtype", "Can view job_subtype activity"),
                ),
            },
        ),
    ]
