# Generated by Django 5.1 on 2025-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_alter_group_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcenter",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobsubtype",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobtype",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="position",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="status",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
