# Generated by Django 5.1 on 2025-03-21 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0003_costcenter_ordering_group_ordering_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="kind",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("administrative", "Administrative"),
                ],
                default="administrative",
                max_length=50,
                verbose_name="kind",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="jobsubtype",
            name="job_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_subtypes",
                to="org.jobtype",
                verbose_name="job type",
            ),
        ),
        migrations.AlterField(
            model_name="jobsubtype",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="jobtype",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="is_payable",
            field=models.BooleanField(
                default=True, help_text="payable", verbose_name="is payable"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
    ]
