# Generated by Django 5.1 on 2025-02-16 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0003_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "accounting_id",
                    models.CharField(
                        help_text="cost center id in accounting system",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="the field must be numeric.", regex="^\\d+$"
                            )
                        ],
                        verbose_name="cost center id",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_costcenter", "Can export cost center"),
                    ("view_activity_costcenter", "Can view cost center activity"),
                ),
            },
        ),
    ]
