# Generated by Django 5.1 on 2025-02-16 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0004_costcenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="order of position", verbose_name="order"
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
                "permissions": (
                    ("export_position", "Can export position"),
                    ("view_activity_position", "Can view position activity"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="costcenter",
            options={
                "ordering": ("accounting_id", "name"),
                "permissions": (
                    ("export_costcenter", "Can export cost center"),
                    ("view_activity_costcenter", "Can view cost center activity"),
                ),
                "verbose_name_plural": "cost_centers",
            },
        ),
    ]
