# Generated by Django 5.1 on 2025-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0004_alter_costcenter_name_alter_group_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="for sorting purposes, you can use the same order for different positions",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="is_payable",
            field=models.BooleanField(default=True, verbose_name="is payable"),
        ),
    ]
