# Generated by Django 5.1 on 2025-02-19 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0005_position_alter_costcenter_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_payable",
                    models.BooleanField(
                        default=True, help_text="payable", verbose_name="payable"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "statuses",
                "ordering": ("is_payable", "name"),
                "permissions": (
                    ("export_status", "Can export status"),
                    ("view_activity_status", "Can view status activity"),
                ),
            },
        ),
    ]
