# Generated by Django 5.1 on 2025-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0005_alter_position_order_alter_status_is_payable"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="is_separated",
            field=models.BooleanField(default=False, verbose_name="is separated"),
        ),
    ]
