# Generated by Django 5.1 on 2025-03-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0007_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="cost_center",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="org.costcenter",
            ),
            preserve_default=False,
        ),
    ]
