# Generated by Django 5.1 on 2025-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_ledger", "Can view ledger report"),
                    ("view_trialbalance", "Can view trial balance report"),
                ),
                "managed": False,
            },
        ),
    ]
