# Generated by Django 5.1 on 2025-02-21 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0003_nationality_alter_city_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_governmental",
                    models.BooleanField(
                        default=True,
                        help_text="is it governmental or private",
                        verbose_name="is governmental",
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False,
                        help_text="is it virtual or ordinary",
                        verbose_name="is virtual",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "school_kinds",
                "ordering": ("name",),
                "permissions": (
                    ("export_schoolkind", "Can export school kind"),
                    ("view_activity_schoolkind", "Can view school kind activity"),
                ),
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="website",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="phone",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="geo.nationality",
                        verbose_name="nationality",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="edu.schoolkind",
                        verbose_name="kind",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "schools",
                "ordering": ("name",),
                "permissions": (
                    ("export_school", "Can export school"),
                    ("view_activity_school", "Can view school activity"),
                ),
            },
        ),
    ]
