# Generated by Django 5.1 on 2025-03-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="address",
            ),
        ),
    ]
