# Generated by Django 5.1 on 2025-02-21 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_specialist",
                    models.BooleanField(
                        default=True,
                        help_text="is a specialist or supporter",
                        verbose_name="is specialist",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_specialization", "Can export specialization"),
                    (
                        "view_activity_specialization",
                        "Can view specialization activity",
                    ),
                ),
            },
        ),
    ]
