# Generated by Django 5.1 on 2025-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0002_school_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="school",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schoolkind",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specialization",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
