# Generated by Django 5.1 on 2025-02-22 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0003_alter_specialization_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="order of degree", verbose_name="order"
                    ),
                ),
                (
                    "is_academic",
                    models.BooleanField(
                        default=True,
                        help_text="is an academic degree",
                        verbose_name="is academic",
                    ),
                ),
            ],
            options={
                "ordering": ("is_academic", "order", "name"),
                "permissions": (
                    ("export_degree", "Can export degree"),
                    ("view_activity_degree", "Can view degree activity"),
                ),
            },
        ),
    ]
