# Generated by Django 5.1 on 2025-03-21 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0003_degree_ordering_school_ordering_schoolkind_ordering_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="schoolkind",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
    ]
