# Generated by Django 5.1 on 2025-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_alter_degree_name_alter_school_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="is_academic",
            field=models.BooleanField(default=True, verbose_name="is academic"),
        ),
        migrations.AlterField(
            model_name="degree",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="for sorting purposes, you can use the same order for different degrees",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="schoolkind",
            name="is_governmental",
            field=models.BooleanField(default=True, verbose_name="is governmental"),
        ),
        migrations.AlterField(
            model_name="schoolkind",
            name="is_virtual",
            field=models.BooleanField(default=False, verbose_name="is virtual"),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="is_specialist",
            field=models.BooleanField(default=True, verbose_name="is specialist"),
        ),
    ]
