# Generated by Django 5.1 on 2025-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0004_degree"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degree",
            options={
                "ordering": ("-is_academic", "order", "name"),
                "permissions": (
                    ("export_degree", "Can export degree"),
                    ("view_activity_degree", "Can view degree activity"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="website",
            ),
        ),
    ]
