# Generated by Django 5.1 on 2025-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0005_alter_degree_options_alter_school_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="degree",
            options={
                "ordering": ("-is_academic", "order", "name"),
                "permissions": (
                    ("export_degree", "Can export degree"),
                    ("view_activity_degree", "Can view degree activity"),
                ),
                "verbose_name": "Degree",
                "verbose_name_plural": "Degrees",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_school", "Can export school"),
                    ("view_activity_school", "Can view school activity"),
                ),
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolkind",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_schoolkind", "Can export school kind"),
                    ("view_activity_schoolkind", "Can view school kind activity"),
                ),
                "verbose_name": "School Kind",
                "verbose_name_plural": "School Kinds",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "ordering": ("-is_specialist", "name"),
                "permissions": (
                    ("export_specialization", "Can export specialization"),
                    (
                        "view_activity_specialization",
                        "Can view specialization activity",
                    ),
                ),
                "verbose_name": "Specialization",
                "verbose_name_plural": "Specializations",
            },
        ),
    ]
