# Generated by Django 5.1 on 2025-07-11 13:00

import apps.core.mixins.save
import apps.core.models.abstracts
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Governorate",
                "verbose_name_plural": "Governorates",
                "ordering": ("name",),
                "permissions": (
                    ("export_governorate", "Can export governorate"),
                    ("view_activity_governorate", "Can view governorate activity"),
                ),
            },
            bases=(
                apps.core.mixins.save.AddCreateActivityMixin,
                apps.core.models.abstracts.UrlsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_local",
                    models.BooleanField(default=False, verbose_name="is local"),
                ),
            ],
            options={
                "verbose_name": "Nationality",
                "verbose_name_plural": "Nationalities",
                "ordering": ("name",),
                "permissions": (
                    ("export_nationality", "Can export nationality"),
                    ("view_activity_nationality", "Can view nationality activity"),
                ),
            },
            bases=(
                apps.core.mixins.save.AddCreateActivityMixin,
                apps.core.models.abstracts.UrlsMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("area", "Area"),
                            ("town", "Town"),
                            ("village", "Village"),
                            ("other", "Other"),
                        ],
                        default="city",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cities",
                        to="geo.governorate",
                        verbose_name="governorate",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ("kind", "name"),
                "permissions": (
                    ("export_city", "Can export city"),
                    ("view_activity_city", "Can view city activity"),
                ),
            },
            bases=(
                apps.core.mixins.save.AddCreateActivityMixin,
                apps.core.models.abstracts.UrlsMixin,
                models.Model,
            ),
        ),
    ]
