# Generated by Django 5.1 on 2025-02-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_city", "Can export city"),
                    ("view_activity_city", "Can view city activity"),
                ),
                "verbose_name_plural": "cities",
            },
        ),
        migrations.AlterModelOptions(
            name="governorate",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("export_governorate", "Can export governorate"),
                    ("view_activity_governorate", "Can view governorate activity"),
                ),
            },
        ),
    ]
