# Generated by Django 5.1 on 2025-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("kind", "name"),
                "permissions": (
                    ("export_city", "Can export city"),
                    ("view_activity_city", "Can view city activity"),
                ),
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CITY", "City"),
                    ("AREA", "Area"),
                    ("TOWN", "Town"),
                    ("VILLAGE", "Village"),
                    ("OTHER", "Other"),
                ],
                default="CITY",
                max_length=10,
            ),
        ),
    ]
