# Generated by Django 5.1 on 2025-02-13 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_city_options_alter_governorate_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="the field must be at least 4 characters long.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_local",
                    models.BooleanField(
                        default=False,
                        help_text="is it local or foreign",
                        verbose_name="is local",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "nationalities",
                "ordering": ("name",),
                "permissions": (
                    ("export_nationality", "Can export nationality"),
                    ("view_activity_nationality", "Can view nationality activity"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="description"
            ),
        ),
    ]
