# Generated by Django 5.1 on 2025-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_city_options_city_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="governorate",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nationality",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="city",
            name="kind",
            field=models.CharField(
                choices=[
                    ("city", "City"),
                    ("area", "Area"),
                    ("town", "Town"),
                    ("village", "Village"),
                    ("other", "Other"),
                ],
                default="city",
                max_length=10,
            ),
        ),
    ]
