# Generated by Django 5.1 on 2025-03-21 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_city_ordering_governorate_ordering_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="governorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="geo.governorate",
                verbose_name="governorate",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="kind",
            field=models.CharField(
                choices=[
                    ("city", "City"),
                    ("area", "Area"),
                    ("town", "Town"),
                    ("village", "Village"),
                    ("other", "Other"),
                ],
                default="city",
                max_length=10,
                verbose_name="kind",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="governorate",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=4,
                        message="the field must be at least 4 characters long.",
                    )
                ],
                verbose_name="name",
            ),
        ),
    ]
